// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hrharsnbombcmwixrgpo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhyaGFyc25ib21iY213aXhyZ3BvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc1MjQwODAsImV4cCI6MjA3MzEwMDA4MH0.YgTdgAjbrd6ZWI26Fw_nXOWxLCj3K6pCMJb1gSysSzI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});